# Generated by Django 5.1.3 on 2024-11-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0002_alter_application_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_photo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
    ]
