# Generated by Django 3.2.25 on 2024-11-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0003_auto_20241109_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
