# Generated by Django 5.1.3 on 2024-11-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0003_remove_application_additional_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='additional_photo/'),
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
