# Generated by Django 5.1.3 on 2024-11-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0004_application_additional_photo_application_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designpro.categories'),
        ),
    ]
