# Generated by Django 3.2.25 on 2024-11-08 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_book_users_who_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_read',
        ),
        migrations.AddField(
            model_name='book',
            name='user_who_read',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
